[workspace]
members = [
    "socket",               # 01-BPF_PROG_TYPE_SOCKET_FILTER
    "kprobe",
    "sk_skb",               # 14-BPF_PROG_TYPE_SK_SKB
    "tracing/fentry",
    "tracing/iter",         

    "sk_lookup",
    "lsm",
    "btfparse",
]
