[package]
name = "sk_msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libbpf-rs = "0.20"

[build-dependencies]
libbpf-cargo = "0.20"
bindgen = "0.60.1"